---
- hosts: cugergz.chunibyo.xyz
  vars:
    repo_folder: /root/Panel
  remote_user: root
  tasks:

    - name: "Create directory if not exists"
      file:
        path: "{{ repo_folder }}"
        state: directory
        mode: 0755
        group: root
        owner: root

    - name: kill old process
      shell: ps aux | grep main.p[y] | awk '{print $2}' | xargs kill
      ignore_errors: true

    - name: clone repository
      git:
        repo: https://github.com/chunibyo-wly/LinuxControlPanel.git
        dest: "{{ repo_folder }}"
        update: yes
        force: yes
        version: master

    - name: create python virtualenv
      pip:
        requirements: "{{ repo_folder }}/requirements.txt"
        virtualenv: "{{ repo_folder }}/venv"
        virtualenv_command: /usr/bin/python3 -m venv

    - name: install ftp
      shell: "sh {{ repo_folder }}/script/install_ftp.sh"

    - name: install nginx
      shell: "sh {{ repo_folder }}/script/install_nginx.sh"

    - name: install cron
      shell: "sh {{ repo_folder }}/script/install_crontab.sh"

    - name: create database
      shell: "cd {{ repo_folder }} && sudo venv/bin/python db/init.py"

    - name: install ufw
      shell: "sh {{ repo_folder }}/script/install_ufw.sh"

    - name: start server
      shell: "cd {{ repo_folder }} && nohup sudo {{ repo_folder }}/venv/bin/python main.py > /tmp/LinuxControlPanel.log 2>&1 &"


